### ISSUE TITLE
@effectful/serialization does not work in browser because `global` is missing

### ISSUE THREAD

**Issue by pfgithub** [awto/effectfuljs#29]
rather than using `global` directly, it should either use `globalThis` (supported in node and browser) or `typeof window === "undefined" ? global : window`

**Comment by awto** [comment]
thanks! this is fixed in 1.4.5

**Comment by pfgithub** [comment]
That was really fast, wow. Unfortunately, there are still some more that weren't changed like this https://github.com/awto/effectfuljs/blob/3ec9387a4452274701b9ab8a858162643e7b7755/packages/serialization/src/main.ts#L1801

If you have typescript support in your editor, I think you should be able to add `let global;` at the top of the file and then f2 rename `global` to `globalThis` to catch all of them.

**Comment by awto** [comment]
oops, now (I believe) everything should be finally ok, in 1.4.6

**Comment by pfgithub** [comment]
Thanks!
