### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by goodmind** [awto/effectfuljs#6]
Is it possible to support Flow/TypeScript?

**Comment by awto** [comment]
Of course, I already use this to compile TypeScript code in my project. EffectfulJS doesn't extend JS syntax so it works for any language transpiling to JS.

There are long-term plans to utilize TypeScript for type-driven code generation, I did preliminary experiments here [awto/TypeScriptWithImplicits](https://github.com/awto/TypeScriptWithImplicits). This would unlock a lot of other useful features.
